---
- src: https://gitlab.home.fr/myproject/ansible-role-icinga2.git
  scm: git
  version: c2959c02b0deaa8576b2319295ba4fd9ae2681f7

- src: https://gitlab.home.fr/myproject/ansible-role-mariadb.git
  scm: git
  version: d84edb37f9f4f906c0628a9ca329d733a51b37bd
